language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies
before_install:
  - pip install --upgrade pip
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
install:
  - pip install -r requirements.txt
  - python setup.py install 
script: "nosetests"
notifications:
  email: false

